name: pipedream-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - gemmi
  - jinja2
  - matplotlib
  - numpy
  - pandas
  - paramiko
  - plotly
  - pyyaml
  - rdkit
  - scikit-learn
  - tqdm